name: Daily LeetCode Solver

on:
  schedule:
    # Run at 1:00 AM UTC daily
    - cron: '0 1 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  solve-leetcode:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Create .env file
        run: |
          echo "LEETCODE_SESSION=${{ secrets.LEETCODE_SESSION }}" > .env
          echo "CSRF_TOKEN=${{ secrets.CSRF_TOKEN }}" >> .env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
      
      - name: Build and run Docker container
        run: |
          docker build -t leetcode-bot .
          docker run --shm-size=2g -v ${{ github.workspace }}/screenshots:/app/screenshots leetcode-bot
      
      - name: Upload screenshot artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/
          retention-days: 7
      
      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: leetcode_bot.log
          retention-days: 7