
on:
  schedule:
    - cron: "0 3 * * *" # 9 AM IST = 3:00 UTC
  workflow_dispatch:

jobs:
  solve_leetcode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xvfb x11-utils xclip
          pip install -r requirements.txt

      - name: Run LeetCode Auto Solver
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          xvfb-run --auto-servernum python3 leetcode_bot.py
