name: Daily LeetCode Solver

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 9:00 AM IST (3:00 AM UTC)
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run-leetcode-bot:
    runs-on: ubuntu-latest

    env:
      LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
      CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xclip
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run LeetCode Bot
        run: |
          xvfb-run python leetcode_bot.py
