name: Daily LeetCode Solver

on:
  schedule:
    # Runs at 8:00 AM UTC every day (adjust to your preferred time)
    - cron: '0 8 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  solve:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y wget xvfb unzip gpg

    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > google.gpg
        sudo install -o root -g root -m 644 google.gpg /etc/apt/trusted.gpg.d/
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Run LeetCode bot
      env:
        LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        python leetcode_bot.py
